version: "1.0"
info:
  model: int-scaffold
packages:
- name: BtestProject
  gitServerName: ICAccount0928
  gitUrl: https://github.com/MeghaRaj69/BtestProject
  gitUsername: MeghaRaj69
  gitBranch: main
